from time import sleep
qta, prezzo_unitario = map(float,input("Inserisci quantità articoli e prezzo unitario: ").split())
codice_operatore = int(input("Inserisci codice operatore cassa: "))
giorno, mese, anno = map(int,input("Inserisci la data di oggi GG/MM/AAAA: ").split("/"))
tot = qta * prezzo_unitario
print("=== CASSA AUTOMATICA - TERMINALE 01 ===")
print("\nElaborazione scontrino fiscale in corso", end="", flush=True)
sleep(2)
print(".", end="", flush=True)
sleep(2)
print(".", end="", flush=True)
sleep(2)
print(".", end="", flush=True)
sleep(2)
print(" COMPLETATA!\n")
print("--- SCONTRINO FISCALE ---")
print(f"Giorno transazione: {giorno}", mese, anno, sep="/")
print(f"Operatore Cassa: {codice_operatore}")
print(f"Totale da pagare: {tot:.2f} €")